name: On push commitlint
on: [pull_request]

jobs:
    commit_lint:
        runs-on: ubuntu-latest
        outputs:
            lint_result: ${{steps.commit-lint.outputs.result}}
        steps:
            -   id: checkout
                uses: actions/checkout@v3
            -   id: commit-lint
                uses: wagoid/commitlint-github-action@v5
            -   run: echo ${{steps.commit-lint.outputs.results}}
    